### ISSUE TITLE
麻烦能否支持下MAC m1 的 arm64

### ISSUE THREAD

**Issue by milesmao233** [geatpy-dev/geatpy#246]
显示 awGA.cpython-38-darwin.so 不支持 arm64

**Comment by zeroraiser** [comment]
Thank you. Your email is received and will be handled as soon as possible

**Comment by xm1490** [comment]
来信收到。谢谢。徐明

**Comment by Jintao-Qu** [comment]
您好，非常喜欢你们的框架，感谢您在进化计算作出的贡献！近期换了m1 mac,请在方便时发我一份安装包，万分感谢。

**Comment by geatpy-dev** [comment]
我后面找个M1 macbook编译一份。

**Comment by Jintao-Qu** [comment]
谢谢，如果需要我可以teamviewer远程提供我的设备。再次感谢！
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Sun, Dec 12, 2021 10:27 AM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [geatpy-dev/geatpy] 麻烦能否支持下MAC m1 的 arm64 (Issue #246)

&nbsp;



 
我后面找个M1 macbook编译一份。
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by rj03hou** [comment]
工作环境用m1，并且强依赖于m1，🙏

**Comment by geatpy-dev** [comment]
近日就会推出2.7.0，届时会编译M1 MacOS版本。

**Comment by rj03hou** [comment]
> 近日就会推出2.7.0，届时会编译M1 MacOS版本。

谢谢，十分感谢。

**Comment by geatpy-dev** [comment]
2.7.0已经支持M1的Python3.8和3.9。
